export const GET_PAYMENT_METHODS = "pm/GET_PAYMENT_METHODS"
export const SET_AMOUNT = "pm/SET_AMOUNT"
export const SET_STEP = "pm/SET_STEP"
export const SET_LOADING = "pm/SET_LOADING"
export const SET_ERROR = "pm/SET_ERROR"
export const CONFIRM = "pm/CONFIRM"